language: node_js
node_js:
  - '12'
dist: 'xenial'
os: 'linux'
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
  - yarn add global travis-ci-cloudfront-invalidation
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  cleanup: true
  local_dir: public
  on:
    branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s
    $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p
    $TRAVIS_PULL_REQUEST
